version: 2.1

orbs:
  node: circleci/node@10.22.1-browsers-legacy

jobs:
  build:
    executor:
      name: node/default

    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  build:
    jobs:
      - build

